# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.TextField()),
                ('statuses_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('verified', models.BooleanField()),
                ('verified_type', models.IntegerField()),
                ('auth_token', models.TextField()),
                ('expired_time', models.IntegerField()),
            ],
        ),
    ]
